#!/bin/bash
#
# Pre-commit hooks

# Check branch name

DEFAULT_BRANCH_NAME=`git rev-parse --abbrev-ref HEAD`
BRANCH_NAME=${1:-$DEFAULT_BRANCH_NAME}

REGEXP="^header$|^footer$|^content-container$|^top-section$|^bottom-section$"

BRANCH_NAME_LENGTH=`echo $BRANCH_NAME | grep -E $REGEXP | wc -c`

if [ ${BRANCH_NAME_LENGTH} -eq 0 ] ; then
  echo "The name of the current branch does not match one of the tasks in the course."
  echo
  echo "Current branch name:" $BRANCH_NAME
  echo
  echo "Accepted branch names are:"
  echo "  header"
  echo "  footer"
  echo "  content-container"
  echo "  top-section"
  echo "  bottom-section"
  echo
  exit 1
fi
